### ISSUE TITLE
Hard-coded path in targets/xenret script

### ISSUE THREAD

**Issue by standage** [BrendelGroup/TRegGA#1]
It's easy enough for us to change `/home/TRegGA/prj/` to `/some/other/path/TRegGA/`, but we should not burden ourselves or other users with such trivial tasks.

**Comment by vpbrendel** [comment]
Provide file mf-TRegGA.inc:

TRegGA_DIR = /home/TReGA/prj

Then near the top of Makefile_TReGA-orig (all all the other makefiles):

include mf-TRegGA.inc

(or include ../mf-TRegGA.inc)

Then we can update the makefiles while leaving the directory conventions 
untouched on a given machine.
Same for paths to binaries.

Volker

On 8/25/2015 1:39 PM, Daniel Standage wrote:

> It's easy enough for us to change |/home/TRegGA/prj/| to 
> |/some/other/path/TRegGA/|, but we should not burden ourselves or 
> other users with such trivial tasks.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/BrendelGroup/TRegGA/issues/1.

## 

Volker Brendel
Professor of Biology and Computer Science
Indiana University
Department of Biology&  School of Informatics and Computing
212 South Hawthorne Drive
Simon Hall 205C
Bloomington, IN 47405

Tel.: (812) 855-7074
http://brendelgroup.org/
